# Generated by Django 3.1.5 on 2021-01-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_auto_20210127_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='requirements',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(),
        ),
    ]
